site_name: Yorek's
site_description: 'An Android Developer.'
site_author: 'Yorek Liu'
site_url: 'https://blog.yorek.xyz'

# repo_name: 'YorekLiu/yorekliu.github.io'
# repo_url: 'https://github.com/YorekLiu/yorekliu.github.io'
edit_uri: ""

copyright: '&copy; 2022 Yorek'

theme:
  name: 'material'
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Noto Sans SC
    code: JetBrains Mono
  language: 'zh'
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
  logo: assets/images/favicon.webp
  icon:
    repo: material/github
  favicon: assets/images/favicon.webp
  custom_dir: overrides

plugins:
  - search:
      prebuild_index: true
  - git-revision-date-localized
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: material/github
      link: https://github.com/YorekLiu
    - icon: material/email
      link: lyytogether@gmail.com
  manifest: manifest.webmanifest
  analytics:
    provider: google
    property: UA-155096376-1

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Page tree
nav:
  - Android:
    - 三方库系列: 
      - android/3rd-library/3rd-library-source-code.md
      - android/3rd-library/matrix.md
      - android/3rd-library/matrix-trace.md
      - android/3rd-library/matrix-trace-plugin.md
      - android/3rd-library/matrix-io.md
      - android/3rd-library/matrix-resource.md
      - android/3rd-library/matrix-apk-checker.md
      - android/3rd-library/matrix-sqlitelint.md
      - android/3rd-library/andresguard.md
      - android/3rd-library/hprof-shrink.md
      - android/3rd-library/okhttp.md
      - android/3rd-library/retrofit.md
      - android/3rd-library/rxjava&rxandroid.md
      - android/other/RxJava.md
      - android/3rd-library/glide1.md
      - android/3rd-library/glide2.md
      - android/3rd-library/glide3.md
      - android/3rd-library/glide4.md
      - android/3rd-library/glide5.md
      - android/3rd-library/glide6.md
      - android/3rd-library/glide7.md
      - android/3rd-library/migrate-to-glide.md
      - android/3rd-library/eventbus.md
      - android/3rd-library/leakcanary.md
      - android/3rd-library/permissiondispatcher.md
      - android/other/constraintlayout.md
      - android/other/dagger2.md
      - android/3rd-library/hotfix.md
    - framework系列: 
      - android/framework/Android四大组件(1).md
      - android/framework/Android四大组件(2).md
      - android/framework/Android四大组件(3).md
      - android/framework/Android四大组件(4).md
      - android/framework/IPC机制.md
      - android/framework/View的事件体系.md
      - android/framework/View的绘制原理.md
      - android/framework/RemoteViews.md
      - android/framework/Drawable.md
      - android/framework/Android动画.md
      - android/framework/Window与WindowManager.md
      - android/framework/四大组件启动过程.md
      - android/framework/Android消息机制.md
      - android/framework/Android线程与线程池.md
      - android/framework/Bitmap的缓存与加载.md
      - android/framework/JNI与NDK.md
      - android/framework/性能优化.md
      - android/framework/binder1-mediaservice.md
      - android/framework/binder2.md
    - 杂记:
      - android/other/commands.md
      - android/other/android-tv.md
      - android/other/annotation.md
      - android/other/best_throttle_in_mvvm.md
      - android/other/android-jenkins.md
      - android/other/SystemProrities.md
      - android/other/recyclerview-cache.md
      - android/other/recyclerview-item-docoration.md
      - android/other/recyclerview-others.md
      - android/other/RecyclerView-Sort&Delete.md
      - android/other/FAB-Behavior.md
      - android/other/nestedscrolling.md
      - android/other/porterduff.md
      - android/other/runtime.md
      - android/other/android_alias.md
      - android/other/Android-Development-Tool.md
      - android/other/FileProvider.md
      - android/other/Android判断导航栏高度.md
      - android/other/Android图片选择器.md
      - android/other/Android底部导航栏框架.md
      - android/other/Android搜索栏的实现.md
      - android/other/Android暂停音乐播放器的播放.md
      - android/other/Android滑动返回实践.md
      - android/other/Android程序反编译.md
      - android/other/Android通讯录快速读取.md
      - android/other/soft-keyboard-in-app.md
      - android/other/腾讯X5内核入坑指南.md
      - android/other/琐碎知识点.md
      - android/other/琐碎知识点2.md
    - 基础知识:
      - android/paid/zsxq/week1-synchronized.md
      - android/paid/zsxq/week2-service.md
      - android/paid/zsxq/week3-activity.md
      - android/paid/zsxq/week4-startActivityForResult.md
      - android/paid/zsxq/week5-view.md
      - android/paid/zsxq/week6-gradle.md
      - android/paid/zsxq/week7-serialization.md
      - android/paid/zsxq/week10-classloader.md
      - android/paid/zsxq/week11-binder.md
      - android/paid/zsxq/week12-retrofit-okhttp.md
      - android/paid/zsxq/week14-jvm-gc.md
      - android/paid/zsxq/week16-keep-app-alive.md
      - android/paid/zsxq/week17-android-components.md
      - android/paid/zsxq/week20-network-protocol.md
      - android/paid/zsxq/week21-mvc&mvp&mvvm.md
      - android/paid/zsxq/week22-android-studio-build.md
      - android/paid/zsxq/week23-load-large-bitmap.md
      - java/generics-java-kotlin.md
      - java/java-collections.md
      - java/java-foundation.md
    - Android开发高手课:
      - android/paid/master/index.md
      - android/paid/master/crash_1.md
      - android/paid/master/crash_2.md
      - android/paid/master/memory_1.md
      - android/paid/master/memory_2.md
      - android/paid/master/stuck_1.md
      - android/paid/master/stuck_2.md
      - android/paid/master/stuck_3.md
      - android/paid/master/start_1.md
      - android/paid/master/start_2.md
      - android/paid/master/io_1.md
      - android/paid/master/io_2.md
      - android/paid/master/io_3.md
      - android/paid/master/storage_1.md
      - android/paid/master/storage_2.md
      - android/paid/master/storage_3.md
      - android/paid/master/network_1.md
      - android/paid/master/network_2.md
      - android/paid/master/network_3.md
      - android/paid/master/battery_1.md
      - android/paid/master/battery_2.md
      - android/paid/master/ui_1.md
      - android/paid/master/ui_2.md
      - android/paid/master/package_1.md
      - android/paid/master/package_2.md
      - android/paid/master/compile.md
      - android/paid/master/bytecode.md
      - android/paid/master/native_hook.md
  - Flutter:
    - flutter/flutter_first_project_1.md
    - flutter/flutter_first_project_2.md
    - flutter/flutter_first_project_3.md
    - flutter/flutter_first_project_4.md
  - LeetCode:
    - leetcode/index.md
    - leetcode/code_interviews_1.md
    - leetcode/code_interviews_3.md
    - leetcode/code_interviews_4.md
    - leetcode/code_interviews_5.md
    - leetcode/code_interviews_6.md
    - leetcode/array.md
    - leetcode/leetcode1-10.md
    - leetcode/leetcode11-20.md
    - leetcode/leetcode21-30.md
    - leetcode/leetcode31-40.md
    - leetcode/leetcode41-50.md
    - leetcode/leetcode51-60.md
    - leetcode/leetcode61-70.md
    - leetcode/leetcode71-80.md
    - leetcode/leetcode81-90.md
    - leetcode/leetcode91-100.md
    - leetcode/leetcode101-110.md
    - leetcode/leetcode111-120.md
  - Books:
    - Design Pattern:
      - design-pattern/design-pattern.md
      - design-pattern/design-principle.md
      - design-pattern/singleton.md
      - design-pattern/builder.md
      - design-pattern/prototype.md
      - design-pattern/factory-method.md
      - design-pattern/abstract-factory.md
      - design-pattern/proxy.md
      - design-pattern/composite.md
      - design-pattern/adapter.md
      - design-pattern/decorator.md
      - design-pattern/flyweight.md
      - design-pattern/facade.md
      - design-pattern/bridge.md
      - design-pattern/strategy.md
      - design-pattern/state.md
      - design-pattern/chain-of-responsibility.md
      - design-pattern/interpreter.md
      - design-pattern/command.md
      - design-pattern/observer.md
      - design-pattern/memento.md
      - design-pattern/iterator.md
      - design-pattern/template-method.md
      - design-pattern/visitor.md
      - design-pattern/mediator.md
      - design-pattern/confusing-design-pattern.md
    - Effective Java:
      - effective-java/effective-java.md
      - effective-java/chapter1.md
      - effective-java/chapter2.md
      - effective-java/chapter3.md
    - JVM:
      - jvm/jvm-content.md
      - jvm/java-memory-area-oom.md
      - jvm/java-gc.md
      - jvm/class-struct.md
      - jvm/load-class.md
    - Refactoring:
      - refactoring/refactoring.md